package org.apache.maven.plugin.ear;

import org.apache.maven.artifact.Artifact;
import org.codehaus.plexus.util.xml.XMLWriter;

/*
 * Copyright 2001-2005 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * The {@link EarModule} implementation for a JBoss Hibernate archive.
 *
 * @author <a href="snicoll@apache.org">Stephane Nicoll</a>
 * @version $Id$
 */
public class HarModule
    extends AbstractEarModule
{
    public HarModule()
    {
    }

    public HarModule( Artifact a )
    {
        super( a );
    }

    public void appendModule( XMLWriter writer, String version )
    {
        // No entry is generated by this artifact ; it should be
        // defined in the jboss-app.xml.
        // See http://docs.jboss.org/jbossas/getting_started/v4/html/hibernate.html
    }

    protected String getType()
    {
        return "har";
    }
}
